[package]
name = "ic-processes-panel"
version = "0.1.0"
edition = "2021"
description = "Shows running processes in a panel as a table"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ic-plugin-api = { workspace = true }
sysinfo = "0.29"

[features]
default = ["export-abi"]
export-abi = []
